apiVersion: app/v1
kind: Deployment
metadata:
  label:
    app: nginx-deployment
name: nginx-deployment
specs:
  replicas: 10
    selector:
      matchLabels:
      app: nginx-deployment
  strategies:
    type: recreate
  template:
    metadata:
    label:
      app: nginx-deployment
    specs:
      containers:
      - image: nginx 1.15.0
        name: nginx
        resources:
          limits:
            cpu: "1.5"
            memory: 256Ml
          requests:
            cpu: 1.25
            memory: 128Ml
